'use server';
import {redirect} from 'next/navigation';import {revalidatePath} from 'next/cache';import {database} from '@/lib/supabase';import {officeSession,adminSession,session} from '@/lib/auth';import {customerInput,locationInput,equipmentInput,equipmentUpdate,photoType,PHOTO_MAX_BYTES,priceTaskInput,pricingSettingsInput,trades} from '@/lib/validation';import {SITE,EQ,PHOTO_BUCKET} from '@/lib/fields';import {z} from 'zod';import {randomUUID} from 'node:crypto';import {planImport,type ImportPlan,type ExistingCustomer} from '@/lib/hcp';type Trade=typeof trades[number];
export async function login(form:FormData){const db=await database();const email=String(form.get('email')??'').trim();const password=String(form.get('password')??'');const {error}=await db.auth.signInWithPassword({email,password});if(error)redirect('/login?error=login');redirect('/');}
export async function logout(){const db=await database();const {error}=await db.auth.signOut();if(error)throw new Error('Could not sign out.');redirect('/login');}
function fields(form:FormData){return Object.fromEntries(form.entries());}
function finish(id:string,error:boolean){revalidatePath('/');revalidatePath('/customers/'+id);redirect('/customers/'+id+(error?'?error=save':'?saved=1'));}
export async function saveCustomer(form:FormData){const {db}=await officeSession();const raw=fields(form);const parsed=customerInput.safeParse(raw);if(!parsed.success)throw new Error('Customer fields are invalid. A parent is required for parent billing.');const {id,...row}=parsed.data;const record={...row,parent_id:row.parent_id||null};const result=id?await db.from('customers').update(record).eq('id',id).select('id').single():await db.from('customers').insert(record).select('id').single();if(result.error||!result.data)throw new Error('Customer could not be saved. Check parent-account relationships.');finish(result.data.id,false);}
export async function saveLocation(form:FormData){const {db}=await officeSession();const p=locationInput.safeParse(fields(form));if(!p.success)throw new Error('Location fields are invalid.');const {error}=await db.from('locations').insert(p.data);finish(p.data.customer_id,!!error);}
type Db=Awaited<ReturnType<typeof database>>;
function equipmentRow(trade:Trade,{extra_value,...row}:{extra_value:string,type:string,location_id:string,year:number|'',warranty_date:string}&Record<string,unknown>){if(!EQ[trade].types.includes(row.type)||!EQ[trade].extra.o.includes(extra_value))throw new Error('Invalid equipment type or trade detail.');return {...row,location_id:row.location_id||null,year:row.year===''?null:row.year,warranty_date:row.warranty_date||null,extra:{[EQ[trade].extra.k]:extra_value}};}
// Stores a data plate photo in the private bucket under <customer>/<equipment>/. Returns null when no photo was chosen.
async function uploadPhoto(db:Db,customerId:string,equipmentId:string,file:FormDataEntryValue|null){if(!(file instanceof File)||file.size===0)return null;if(file.size>PHOTO_MAX_BYTES)throw new Error('Photo is too large. Use a photo under 5 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const kind=photoType(bytes);if(!kind)throw new Error('That file is not a JPEG, PNG or WebP photo.');const path=`${customerId}/${equipmentId}/${randomUUID()}.${kind}`;const {error}=await db.storage.from(PHOTO_BUCKET).upload(path,bytes,{contentType:kind==='jpg'?'image/jpeg':'image/'+kind});if(error)throw new Error('Photo could not be uploaded.');return path;}
export async function saveEquipment(form:FormData){const {db}=await session();const p=equipmentInput.safeParse(fields(form));if(!p.success)throw new Error('Equipment fields are invalid.');const {customer_id,trade,...rest}=p.data;const row=equipmentRow(trade,rest);const id=randomUUID();const photo_path=await uploadPhoto(db,customer_id,id,form.get('photo'));const {error}=await db.from('equipment').insert({...row,id,customer_id,trade,...(photo_path?{photo_path}:{})});if(error&&photo_path)await db.storage.from(PHOTO_BUCKET).remove([photo_path]);finish(customer_id,!!error);}
export async function updateEquipment(form:FormData){const {db}=await session();const p=equipmentUpdate.safeParse(fields(form));if(!p.success)throw new Error('Equipment fields are invalid.');const {id,...rest}=p.data;const {data:current,error:readError}=await db.from('equipment').select('*').eq('id',id).single();if(readError||!current)redirect('/denied?reason=customer');const row=equipmentRow(current.trade,rest);const photo_path=await uploadPhoto(db,current.customer_id,id,form.get('photo'));const {error}=await db.from('equipment').update(photo_path?{...row,photo_path}:row).eq('id',id);const stale=error?photo_path:photo_path&&current.photo_path;if(stale)await db.storage.from(PHOTO_BUCKET).remove([stale]);finish(current.customer_id,!!error);}
export async function saveSite(form:FormData){const {db}=await session();const id=z.uuid().parse(form.get('customer_id'));const trade=z.enum(trades).parse(form.get('trade'));const details:Record<string,string>={};for(const field of SITE[trade]){const value=z.string().max(500).parse(String(form.get(field.k)??''));if(value&&field.o&&!field.o.includes(value))throw new Error('Invalid site option.');if(value&&field.t==='date')z.iso.date().parse(value);if(value&&field.t==='number')z.coerce.number().min(0).parse(value);details[field.k]=value;}const {error}=await db.from('site_details').upsert({customer_id:id,trade,details},{onConflict:'customer_id,trade'});finish(id,!!error);}
// Housecall Pro import. Preview and import both re-read the file with the same rules; nothing is saved until the office confirms.
export type ImportPreview={error:string}|{csv:string;plan:ImportPlan}|null;
const IMPORT_MAX_BYTES=5*1024*1024;
async function existingCustomers(db:Db):Promise<ExistingCustomer[]>{const {data,error}=await db.from('customers').select('*');if(error)throw new Error('Customers could not be loaded.');return (data??[]).map(c=>({id:c.id,name:c.name,parent_id:c.parent_id,hcp_id:c.hcp_id??null}));}
export async function previewImport(_:ImportPreview,form:FormData):Promise<ImportPreview>{const {db}=await officeSession();const file=form.get('file');if(!(file instanceof File)||file.size===0)return {error:'Choose the customer CSV exported from Housecall Pro.'};if(file.size>IMPORT_MAX_BYTES)return {error:'That file is larger than 5 MB. Split it into smaller files.'};const csv=await file.text();const plan=planImport(csv,await existingCustomers(db));return 'error' in plan?plan:{csv,plan};}
export async function runImport(form:FormData){const {db}=await officeSession();const csv=String(form.get('csv')??'');const plan=planImport(csv,await existingCustomers(db));if('error' in plan||!plan.customers.length)redirect('/import?error=nothing');const ids=new Map(plan.customers.map(c=>[c.ref,randomUUID()]));const payload=plan.customers.map(({ref,parent_ref,parent_id,locations,name,type,phone,email,service_address,billing_address,access_notes,lead_source,hcp_id})=>({id:ids.get(ref),parent_id:parent_ref?ids.get(parent_ref):parent_id,locations,name,type,phone,email,service_address,billing_address,access_notes,lead_source,hcp_id}));const {data,error}=await db.rpc('import_hcp_customers',{payload});if(error)redirect('/import?error=failed');revalidatePath('/');redirect('/?imported='+Number(data));}
// Price book. All writes go through database functions that calculate and store the price, so it can't drift from the formula.
function priceBook(trade:string,status:string):never{revalidatePath('/price-book');redirect('/price-book?trade='+trade+'&'+status);}
export async function savePriceTask(form:FormData){const {db}=await officeSession();const p=priceTaskInput.safeParse(fields(form));if(!p.success)redirect('/price-book?error=invalid');const t=p.data;const {error}=await db.rpc('save_price_task',{p_id:t.id||null,p_trade:t.trade,p_name:t.name,p_includes:t.includes,p_hours:t.hours,p_parts:t.parts,p_mode:t.mode,p_custom_price:t.mode==='custom'?t.custom_price:null});priceBook(t.trade,error?'error=save':'saved=1');}
export async function deletePriceTask(form:FormData){const {db}=await officeSession();const id=z.uuid().parse(form.get('id'));const trade=z.enum(trades).parse(form.get('trade'));const {error}=await db.rpc('delete_price_task',{p_id:id});priceBook(trade,error?'error=delete':'deleted=1');}
export async function savePricingSettings(form:FormData){const {db}=await adminSession();const p=pricingSettingsInput.safeParse(fields(form));if(!p.success)redirect('/settings?error=invalid');const s=p.data;const {data,error}=await db.rpc('save_pricing_settings',{p_labor_rate:s.labor_rate,p_parts_markup:s.parts_markup,p_card_cover:s.card_cover,p_tech_cost:s.tech_cost,p_target_margin:s.target_margin});revalidatePath('/price-book');redirect(error?'/settings?error=save':'/settings?repriced='+Number(data));}
