'use server';
import {redirect} from 'next/navigation';import {revalidatePath} from 'next/cache';import {database} from '@/lib/supabase';import {officeSession,session} from '@/lib/auth';import {customerInput,locationInput,equipmentInput,trades} from '@/lib/validation';import {SITE,EQ} from '@/lib/fields';import {z} from 'zod';
export async function login(form:FormData){const db=await database();const email=String(form.get('email')??'').trim();const password=String(form.get('password')??'');const {error}=await db.auth.signInWithPassword({email,password});if(error)redirect('/login?error=login');redirect('/');}
export async function logout(){const db=await database();const {error}=await db.auth.signOut();if(error)throw new Error('Could not sign out.');redirect('/login');}
function fields(form:FormData){return Object.fromEntries(form.entries());}
function finish(id:string,error:boolean){revalidatePath('/');revalidatePath('/customers/'+id);redirect('/customers/'+id+(error?'?error=save':'?saved=1'));}
export async function saveCustomer(form:FormData){const {db}=await officeSession();const raw=fields(form);const parsed=customerInput.safeParse(raw);if(!parsed.success)throw new Error('Customer fields are invalid. A parent is required for parent billing.');const {id,...row}=parsed.data;const record={...row,parent_id:row.parent_id||null};const result=id?await db.from('customers').update(record).eq('id',id).select('id').single():await db.from('customers').insert(record).select('id').single();if(result.error||!result.data)throw new Error('Customer could not be saved. Check parent-account relationships.');finish(result.data.id,false);}
export async function saveLocation(form:FormData){const {db}=await officeSession();const p=locationInput.safeParse(fields(form));if(!p.success)throw new Error('Location fields are invalid.');const {error}=await db.from('locations').insert(p.data);finish(p.data.customer_id,!!error);}
export async function saveEquipment(form:FormData){const {db}=await session();const p=equipmentInput.safeParse(fields(form));if(!p.success)throw new Error('Equipment fields are invalid.');const {extra_value,...row}=p.data;if(!EQ[row.trade].types.includes(row.type)||!EQ[row.trade].extra.o.includes(extra_value))throw new Error('Invalid equipment type or trade detail.');const {error}=await db.from('equipment').insert({...row,location_id:row.location_id||null,year:row.year===''?null:row.year,warranty_date:row.warranty_date||null,extra:{[EQ[row.trade].extra.k]:extra_value}});finish(row.customer_id,!!error);}
export async function saveSite(form:FormData){const {db}=await session();const id=z.uuid().parse(form.get('customer_id'));const trade=z.enum(trades).parse(form.get('trade'));const details:Record<string,string>={};for(const field of SITE[trade]){const value=z.string().max(500).parse(String(form.get(field.k)??''));if(value&&field.o&&!field.o.includes(value))throw new Error('Invalid site option.');if(value&&field.t==='date')z.iso.date().parse(value);if(value&&field.t==='number')z.coerce.number().min(0).parse(value);details[field.k]=value;}const {error}=await db.from('site_details').upsert({customer_id:id,trade,details},{onConflict:'customer_id,trade'});finish(id,!!error);}
