import {EQ,TRADE_NAMES} from '@/lib/fields';import {trades} from '@/lib/validation';import {saveEquipment,updateEquipment} from '@/app/actions';import {PhotoInput} from '@/components/PhotoInput';
// Equipment list and add/edit forms, shared by the customer page and the job page.
// returnTo (a /jobs/<id> path) sends the person back to the job after saving instead of to the customer page.
type Trade=typeof trades[number];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type EquipmentRow=Record<string,any>;
type Place={customerId:string;locations:{id:string;name:string}[];returnTo?:string};
// Photos are served by /photos/<equipment id>, which checks the login on every view. ?v= changes after a retake so the new photo shows.
export const photoUrl=(eq?:{id:string;photo_path?:string|null})=>eq?.photo_path?`/photos/${eq.id}?v=${encodeURIComponent(eq.photo_path.split('/').pop()!)}`:null;
// One form for adding and editing. Trade can't change after saving because the type and trade detail depend on it.
export function equipmentForm({customerId,locations,returnTo}:Place,trade:Trade,locationId:string,eq?:EquipmentRow){return <form action={eq?updateEquipment:saveEquipment}>{eq?<input type="hidden" name="id" value={eq.id}/>:<><input type="hidden" name="customer_id" value={customerId}/><input type="hidden" name="trade" value={trade}/></>}{returnTo&&<input type="hidden" name="return_to" value={returnTo}/>}<p className="muted">Read it off the data plate. Snap a photo so the office can look up parts and warranty later.</p><PhotoInput current={photoUrl(eq as {id:string;photo_path?:string|null}|undefined)}/><div className="grid"><label className="field">Type<select name="type" defaultValue={eq?.type}>{EQ[trade].types.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Location<select name="location_id" defaultValue={eq?eq.location_id??'':locationId}><option value="">Main property</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{[['brand','Brand'],['model','Model'],['serial','Serial'],['year','Year'],['size',EQ[trade].size],['property_location','Location on property'],['warranty_date','Warranty date']].map(([key,label])=><label className="field" key={key}>{label}<input name={key} defaultValue={eq?.[key]??''} type={key==='year'?'number':key==='warranty_date'?'date':'text'} min={key==='year'?1900:undefined} max={key==='year'?2100:undefined} maxLength={500}/></label>)}<label className="field">{EQ[trade].extra.l}<select name="extra_value" defaultValue={eq?.extra?.[EQ[trade].extra.k]}>{EQ[trade].extra.o.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Condition<select name="condition" defaultValue={eq?.condition}>{['Good','Fair','Poor','Needs replacement'].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="field">Notes<textarea name="notes" defaultValue={eq?.notes??''} maxLength={2000}/></label><button className="primary">Save equipment</button></form>;}
export function equipmentRows(place:Place,list:EquipmentRow[]){return list.map(eq=>{const url=photoUrl(eq as {id:string;photo_path?:string|null});return <details key={eq.id}><summary>{TRADE_NAMES[eq.trade]} · {eq.type} · {eq.brand}</summary><div className="eqphoto">{url?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt={'Data plate photo, '+eq.type}/></a>:<span className="eqph">No photo</span>}</div><dl>{[['Model',eq.model],['Serial',eq.serial],['Year',eq.year],['Size',eq.size],[EQ[eq.trade].extra.l,eq.extra?.[EQ[eq.trade].extra.k]],['Condition',eq.condition],['On property',eq.property_location],['Warranty',eq.warranty_date],['Notes',eq.notes]].map(([label,value])=><div key={String(label)} style={{display:'contents'}}><dt>{label}</dt><dd>{String(value||'—')}</dd></div>)}</dl><details><summary>Edit equipment</summary>{equipmentForm(place,eq.trade,'',eq)}</details></details>});}
export function addEquipmentForms(place:Place,locationId:string,only?:Trade){return (only?[only]:trades).map(trade=><details key={trade}><summary>Add {TRADE_NAMES[trade]} equipment</summary>{equipmentForm(place,trade,locationId)}</details>);}
